save_thumbnail_image:
  description: 'Request the lates motion thumbnail from a camera and write it to a file'
  fields:
    entity_id:
      description: 'string (required) camera to get thumbnail from'
      example: 'camera.outdoor'
    filename:
      description: 'string (required) where to save the thumbnail'
      example: '/config/www/thumbnail.png'
    image_width:
      description: 'string (optional) width of Thumbnail image in pixels'
      example: '640'
set_recording_mode:
  description: 'Set recording mode for the camera'
  fields:
    entity_id:
      description: 'string (required) camera to enable recording on'
      example: 'camera.outdoor'
    recording_mode:
      description: '(Optional) Valid options are: always = Always Recording, motion = Only record on motion, never = stop recording. Default value is: motion'
      example: motion
set_ir_mode:
  description: 'Set Infrared Settings for the camera'
  fields:
    entity_id:
      description: 'string (required) camera to enable recording on'
      example: 'camera.outdoor'
    ir_mode:
      description: '(Optional) Valid options are: always_on = IR always on, auto = Automatic, led_off = Automatic wo LEDs, always_off = Always Off. Default value is: auto'
      example: auto
