- platform: influxdb
  host: !secret influx_host
  port: 8086
  database: !secret influx_database
  username: !secret influx_username
  password: !secret influx_password
  queries:
    - name: mean_value_of_basement_temperature
      where: '"entity_id" = ''basement_temperature'' and time > now() - 1h'
      measurement: '"°F"'
      value_template: "{{ value | round(1) }}"
    - name: mean_value_of_basement_humidity
      where: '"entity_id" = ''basement_humidity'' and time > now() - 1h'
      measurement: '"%"'
      value_template: "{{ value | round(1) }}"
  scan_interval: 900
- platform: bhyve
