# Base Configuration
default_config:
http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem

# General Configuration
homeassistant:
    customize: !include customize.yaml
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    name: !secret home_name
    time_zone: America/Indiana/Indianapolis
    unit_system: imperial

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Integrations
cover: !include integrations/cover.yaml
cloudflare: !include integrations/cloudflare.yaml
