default_config:
homeassistant:
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    name: !secret home_name
    time_zone: America/Indiana/Indianapolis
    unit_system: imperial
       
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
