# Base Configuration
default_config:
http:
    ssl_certificate: ssl/fullchain.pem
    ssl_key: ssl/privkey.pem
recorder:
    db_url: !secret db_url

# General Configuration
homeassistant:
    customize: !include customize.yaml
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    name: !secret home_name
    time_zone: America/Indiana/Indianapolis
    unit_system: imperial
    external_url: !secret external_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Integrations
cover: !include integrations/cover.yaml
cloudflare: !include integrations/cloudflare.yaml
dyson: !include integrations/dyson.yaml
lutron_caseta: !include integrations/lutron_caseta.yaml
