# Base Configuration
default_config:
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
recorder:
  db_url: !secret db_url

# General Configuration
homeassistant:
  customize: !include customize.yaml
  external_url: !secret external_url

group: !include groups.yaml
automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
script manual: !include_dir_merge_named scripts
script ui: !include scripts.yaml
scene: !include scenes.yaml
alert: !include alerts.yaml
shell_command: !include shell_commands.yaml

# Integrations
lutron_caseta: !include integrations/lutron_caseta.yaml
ecobee: !include integrations/ecobee.yaml
sensor: !include integrations/sensor.yaml
switch: !include integrations/switch.yaml
binary_sensor: !include integrations/binary_sensor.yaml
ios: !include integrations/ios.yaml
influxdb: !include integrations/influxdb.yaml
input_boolean: !include integrations/input_boolean.yaml
bhyve: !include integrations/bhyve.yaml
lovelace: !include integrations/lovelace.yaml
