# Base Configuration
default_config:
http:
    ssl_certificate: ssl/fullchain.pem
    ssl_key: ssl/privkey.pem
recorder:
    db_url: !secret db_url
influxdb:
    host: !secret influx_host
    port: 8086
    database: !secret influx_database
    username: !secret influx_username
    password: !secret influx_password
    max_retries: 3
    default_measurement: state
    include:
        entities:
            - sensor.basement_temperature
            - sensor.basement_humidity
            - sensor.particulate_matter_2_5um_concentration
            - sensor.particulate_matter_1_0um_concentration
            - sensor.particulate_matter_10_0um_concentration
lovelace:
    mode: yaml

# General Configuration
homeassistant:
    customize: !include customize.yaml
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    name: !secret home_name
    time_zone: America/Indiana/Indianapolis
    unit_system: imperial
    external_url: !secret external_url

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
alert: !include alerts.yaml

# Integrations
cover: !include integrations/cover.yaml
cloudflare: !include integrations/cloudflare.yaml
dyson: !include integrations/dyson.yaml
lutron_caseta: !include integrations/lutron_caseta.yaml
ecobee: !include integrations/ecobee.yaml
sensor: !include integrations/sensor.yaml
ios: !include integrations/ios.yaml
