- alias: 'Turn on the bookshelf lamp 1 hour before sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.front_room_bookshelf_lamp

- alias: 'Turn off the bookshelf lamp at 11PM'
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.front_room_bookshelf_lamp

- alias: "Toggle the table overhead light"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: front_room_mini_button
      event: 1002
  action:
    service: homeassistant.toggle
    entity_id: switch.front_room_table_overhead
