- alias: 'Turn on the bookshelf lamp at 6pm'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.front_room_bookshelf_lamp

- alias: 'Turn off the bookshelf lamp at 11PM'
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.front_room_bookshelf_lamp
