- alias: "Turn on front room lights 1 hour before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: switch.turn_on
    entity_id:
      - switch.front_room_bookshelf_lamp_plug

- alias: "Turn off front room lights at 11PM"
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: switch.turn_off
    entity_id:
      - switch.front_room_bookshelf_lamp_plug

- alias: "Toggle the table overhead light"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: front_room_mini_button
      event: 1002
  action:
    service: homeassistant.toggle
    entity_id: switch.front_room_table_overhead_plug
