- alias: "Turn on front room lights 1 hour before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.front_room_bookshelf_lamp

- alias: "Turn off front room lights at 11PM"
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.front_room_bookshelf_lamp
