- alias: 'Turn on the hallway lamp at 6:30AM'
  trigger:
    platform: time
    at: '06:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.hallway_lamp

- alias: 'Turn off the hallway lamp at 11PM'
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.hallway_lamp
