- alias: "Turn on the countertop lamp at 6:30AM"
  trigger:
    platform: time
    at: "06:30:00"
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen_counter_lamp
      brightness_pct: 35

- alias: "Turn off the countertop lamp at 11PM"
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: light.turn_off
    entity_id: light.kitchen_counter_lamp

- alias: "Kitchen sink light to full brightness when the overhead lights are on"
  trigger:
    - platform: state
      entity_id: light.kitchen_overhead
      to: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen_sink_overhead
      data:
        brightness: 255

- alias: "Kitchen sink light to dim when the overhead lights are off"
  trigger:
    - platform: state
      entity_id: light.kitchen_overhead
      to: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.kitchen_sink_overhead
