- alias: 'Turn on the countertop lamp at 6:30AM'
  trigger:
    platform: time
    at: '06:30:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen_counter
      brightness_pct: 35

- alias: 'Turn off the countertop lamp at 11PM'
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: light.turn_off
    entity_id: light.kitchen_counter
