- alias: Turn on driveway lights when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_driveway
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.driveway_motion_sensor_override
        state: "off"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: "-00:45:00"
          - condition: sun
            before: sunrise
  action:
    service: light.turn_on
    entity_id: group.driveway_floodlights

- alias: Turn off driveway lights 10 minutes after last motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_driveway
    to: "off"
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.driveway_motion_sensor_override
        state: "off"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: "-00:45:00"
          - condition: sun
            before: sunrise
            before_offset: "01:00:00"
  action:
    service: light.turn_off
    entity_id: group.driveway_floodlights

- alias: "Turn on the outdoor Christmas lights 1 hour before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.driveway_string_lights
        state: "unavailable"
  action:
    service: switch.turn_on
    entity_id:
      - switch.plugb2

- alias: "Turn off outdoor Christmas lights at 2AM"
  trigger:
    platform: time
    at: "02:00:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.driveway_string_lights
        state: "unavailable"
  action:
    service: switch.turn_off
    entity_id:
      - switch.driveway_string_lights
