- alias: Turn on driveway lights when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_driveway
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"
      - condition: sun
        before: sunrise
  action:
    service: light.turn_on
    entity_id: group.driveway_lights

- alias: Turn off driveway lights 10 minutes after last motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.motion_driveway
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"
      - condition: sun
        before: sunrise
  action:
    service: light.turn_off
    entity_id: group.driveway_lights
