- alias: "Turn on the Christmas tree 1 hour before sunset if available"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.front_room_christmas_tree
        state: "unavailable"
  action:
    service: switch.turn_on
    entity_id: switch.front_room_christmas_tree

- alias: "Turn off the Christmas tree at 11PM if available"
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.front_room_christmas_tree
        state: "unavailable"
  action:
    service: switch.turn_off
    entity_id: switch.front_room_christmas_tree

- alias: "Turn on the outdoor Christmas lights 1 hour before sunset if available"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.driveway_string_lights
        state: "unavailable"
  action:
    service: switch.turn_on
    entity_id: switch.driveway_string_lights

- alias: "Turn off outdoor Christmas lights at 2AM if available"
  trigger:
    platform: time
    at: "02:00:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.driveway_string_lights
        state: "unavailable"
  action:
    service: switch.turn_off
    entity_id: switch.driveway_string_lights
