- alias: "Toggle both bedside lamps"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: upstairs_bedroom_mini_button
      event: 1002
  action:
    service: homeassistant.toggle
    entity_id:
      - switch.upstairs_bedroom_west_lamp_plug
      - switch.upstairs_bedroom_east_lamp_plug

- alias: "Toggle Annie's bedside lamp"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: upstairs_bedroom_mini_button
      event: 1004
  action:
    service: homeassistant.toggle
    entity_id: switch.upstairs_bedroom_west_lamp_plug
