- alias: "Toggle both bedside lamps"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 6ad012c0fd2c4548aa830605003af78c
      command: single
  action:
    service: homeassistant.toggle
    entity_id:
      - switch.upstairs_bedroom_west_lamp_plug
      - switch.upstairs_bedroom_east_lamp_plug

- alias: "Toggle Annie's bedside lamp"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 6ad012c0fd2c4548aa830605003af78c
      command: double
  action:
    service: homeassistant.toggle
    entity_id: switch.upstairs_bedroom_west_lamp_plug
