- alias: "Toggle both bedside lamps"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 6ad012c0fd2c4548aa830605003af78c
      command: single
  action:
    service: homeassistant.toggle
    entity_id:
      - light.hue_ambiance_candle_1
      - light.hue_ambiance_candle_2

- alias: "Toggle Annie's bedside lamp"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 6ad012c0fd2c4548aa830605003af78c
      command: double
  action:
    service: homeassistant.toggle
    entity_id: light.hue_ambiance_candle_1
