esphome:
  name: basement_aq_sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret basement_aq_sensor_ip

captive_portal:
logger:
api:
ota:

i2c:
  sda: 0
  scl: 2

uart:
  rx_pin: 3
  baud_rate: 9600

sensor:
  - platform: htu21d
    temperature:
      name: "Basement Temperature"
    humidity:
      name: "Basement Humidity"
    update_interval: 20s
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
