substitutions:
  name: upsy-desky-76dbcc
  friendly_name: Upsy Desky 76dbcc
packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/stock.yaml@v2.0.0
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: zPGrznAnb9dVrNfEUIiBh5ycro1T7t/lLBEjaB5FS7A=

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
