substitutions:
  name: upsy-desky-76dbcc
  friendly_name: Upsy Desky 76dbcc
packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/stock.yaml@v4.0.2
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: LlaZXzy/s0Dj2gNNQxfKQ7btsFInHSKt2j7lUCOKeL0=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
